### ISSUE TITLE
Will not work in Android N (7.0)

### ISSUE THREAD

**Issue by ghost** [Telerik-Verified-Plugins/Couchbase-Lite#3]
I'm new to git so forgive me if I'm not following the process correctly, but I have an app that is working fine on Android 4.x, 5.x and 6.x but will not work on 7.x.  I have a file from logcat, but I don't know what all to attach to this post.  Are there any plans on making this work in 7.x?

**Comment by EddyVerbruggen** [comment]
Thanks for the info. This is a fork of the upstream Couchbase Lite repo and that one seems to have recently been updated. Perhaps it now supports Android 7 as well, but you'd need to [test that version](https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin) to be sure. In case the issue is there please open an issue on their repo.

Feel free to link to your log of course. Perhaps there's something obvious in there.

They've squashed all commits it seems, so it's impossible to see any history unfortunately. I also can't tell if there are breaking changes to the JS API unless I test everything. So that may take a while.

I'm curious to learn if you have the same issue on an Android 7 emulator (and which one), that would give me a way to reproduce this.

**Comment by ghost** [comment]
So it wouldn't work on a physical Nexus phone (not sure what model) running Android 7.  It also will not work using the Android SDK emulator for a Nexus 5 device with Android 7.  By the way, I also could not get it to  work on the Android SDK emulator for a Nexus 5 device with Android 6, but it will work on my Samsung Galaxy S5 with Android 6.  Android 5 in the emulator worked fine so I ruled it out as a problem with my emulator.

**Comment by EddyVerbruggen** [comment]
@mb34124 did you try this fork, or [the upstream](https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin) as per my previous comment? Thanks in advance for the clarification!

**Comment by ghost** [comment]
Thank you for your response.  I actually entered a ticket with Telerik.  They were able to reproduce the issue with a sample application I sent them.  They also were able to get the sample app to work after downloading the latest from Couchbaselabs' repo.  They then replied in the ticket with this: "I will contact the people responsible for maintaining Telerik verified plugins marketplace to update them about my findings and request an update of the plugin from the base repository."  I am going to wait until this plugin is updated "officially" before I try to address this issue in my app.  Android 7.0 is new and less than 1% of my users are using it at this time.  Thanks for your help.  I do have one more question though.  What is the oldest API version that the plugin supports?  I found on couchbase's website that it recommends 19 or newer.

**Comment by EddyVerbruggen** [comment]
Hey @mb34124 then we've closed the loop as I have been contacted by Telerik support ;)

So if they indeed verified the upstream repo is working fine with your app then I will (probably) update this fork tomorrow and contact you again.

Thanks for responding so quickly!
Eddy

**Comment by ghost** [comment]
Thank you Eddy!

**Comment by EddyVerbruggen** [comment]
This should all be OK now!

**Comment by ghost** [comment]
Thank you!  I'll check it out soon!
